spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdb}
    username: ${DB_USER:bankuser}
    password: ${DB_PASSWORD:bankpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

liquibase:
  change-log: classpath:db/migration/db.changelog-master.xml

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod}
    accessTokenExpirationMin: 60
  crypto:
    key: ${CARD_ENCRYPTION_KEY:change-me-in-prod}

server:
  port: 8080
