spring:
  datasource:
    url: jdbc:postgresql://bankcards-db:5432/bankcards
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

springdoc:
  swagger-ui:
    persist-authorization: true

app:
  jwt:
    secret: very-secret-for-dev-minimum-32-bita
    accessTokenExpirationMin: 60
  crypto:
    key: very-secret-key-32chars

server:
  port: 8080
